language: ruby
rvm:
- 2.2.4
before_install: gem install bundler -v 1.11.2
script:
- bundle exec rubocop
- bundle exec rspec
deploy:
  provider: rubygems
  api_key:
    secure: BlQ5gVizHGTyDvIoUHe/wZbY9DQ7XZghpyWnhPiSCbI6oypt2EL+kFQr64ZIgZtLcSa1F9inCwUOfyuN4T2bfVxR3EexKNquLrSVzLjF9duC2VrpKmbBi3bQHVN3T6mQVP1fM1ycKRhAB3FzUANFD9dJqYhkOZnv0DUpe2LloNeIytiS2z3/MHODoSbRXecNHIQkQ/sRONYuPP3hK53xf8ju/RbLiIJeFLsKWuZm2zte2ueZGV5C5bwOaYmdoUuF4ew23CTysk7B0tnGtHWpapJFYfWYqy5f552zUeLAv1es8dwrJyDPC6wncNLDi6hTFkFMf6Sjiyc8lF7Cl2rSgFpBi86WVmGXa0N1kQ0XPUp8uVIBwxNeyWOj5ELJAmiqoMvXYtygJZ35XgWA8qTXvLULBihKF0WfkFeXlAy/pF4yTAMV+WZgr8Xf9xIbgvBvBIZqF6sOYiMAAvwDzT4kcpytSzQCPJjuOMi50bhFQZ4lKtNOggts0fadujTZhN3nCMVpieCqqK2jcIs9xEmpT6sDEqBZ83osUevq8H1wD1GnxJs9dCVqlFDAyb4tYYVuvl40jWMSA/PXRg2Bbmv6qcUqG2feNvWc4vZ35T0joc0OZt3n6HOa3ic/yPmNUluCsgpK1NzPUhPeaoqKyDq2Wgf4MoNQ3CnVwn0kU/9F5V0=
  gem: uuidable
  on:
    tags: true
    repo: flant/uuidable
